version: '3'

x-inception-depends-on: &inception-depends-on
  db:
    condition: service_healthy

services:
  db:
    build:
      context: ./requirements/mariadb
      args:
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_USER_PASSWORD: ${MARIADB_USER_PASSWORD}
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    container_name: mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - type: bind
        source: /home/gvitor-s/data/mariadb
        target: /var/lib/mysql
    networks:
      - inception
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mariadb-admin", "-u", "root", "--password=${MARIADB_ROOT_PASSWORD}", "ping", "-h", "localhost"]
      interval: 15s
      retries: 3

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    volumes:
      - v_wordpress:/www/wordpress
    ports:
      - '443:443'
    networks:
      - inception
    depends_on: *inception-depends-on

  web_app:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    environment:
        MARIADB_USER_PASSWORD: ${MARIADB_USER_PASSWORD}
        MARIADB_USER: ${MARIADB_USER}
    ports:
      - '9000:9000'
    volumes:
      - v_wordpress:/www/wordpress
    depends_on: *inception-depends-on
    networks:
      - inception

volumes:
  v_wordpress:

networks:
  inception:
    name: inception
