version: '3.9'

services:
  db:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - v_mariadb:/var/lib/mysql
    networks:
      - inception
    ports:
      - '3306:3306'
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - v_wordpress:/www/wordpress
    ports:
      - '443:443'
    networks:
      - inception
  web_app:
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
        MARIADB_USER_PASSWORD: ${MARIADB_USER_PASSWORD}
        MARIADB_USER: ${MARIADB_USER}
    ports:
      - '9000:9000'
    volumes:
      - v_wordpress:/www/wordpress
    depends_on:
      db:
        condition: service_healthy
    networks:
      - inception

volumes:
  v_mariadb:
  v_wordpress:

networks:
  inception:
    name: inception
